#!/bin/sh
# --- WARNING (versions and timestamps) ---
#
# Do not use timestamps for generating this package version, because it will be
# built on two different machines, and that will cause the version to differ
set -e
fullversion=$(git describe --tags --match '[0-9].[0-9]*')
debchange -m -D unstable --force-distribution -v $fullversion "Automatic build"
debuild -us -uc -b
#git checkout debian/changelog
